services:
  app:
    build: ./app
    depends_on:
      db:
        condition: service_healthy
        restart: true
    environment:
      - DATABASE_HOST=172.18.0.2
      - DATABASE_USER=root
      - DATABASE_PASSWORD=rootpassword
      - DATABASE_NAME=suphours
      - JWT_SECRET=verysecuresecret
      - JWT_EXPIRES_IN=604800  # 7 days in seconds
      - JWT_COOKIE_EXPIRES_IN=7 # 7 days
    ports:
      - "8000:8000"
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules # avoids re-downloading node_modules every time

  db:
    image: mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=rootpassword
      - MARIADB_DATABASE=suphours
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mariadb_data:/var/lib/mysql


volumes:
  mariadb_data:

